# Generated by Django 5.1.1 on 2024-09-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nodo',
            new_name='ClaseNodo',
        ),
    ]
