# Generated by Django 5.1.1 on 2024-09-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clasenodo_grupo_clasenodo_llave_clasenodo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasenodo',
            name='color',
            field=models.CharField(default='GREEN', max_length=20),
        ),
    ]
