# Generated by Django 5.1.1 on 2024-09-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clasenodo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseCBROperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('operacion', models.CharField(default='open', max_length=50)),
                ('id_nodo', models.IntegerField(default=2)),
            ],
        ),
        migrations.AlterField(
            model_name='clasenodo',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='GREEN', max_length=20),
        ),
    ]
