# Generated by Django 5.1.1 on 2024-09-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_clasecbroperacion_alter_clasenodo_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseOperacionTransiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('aper1', models.FloatField()),
                ('fasea', models.FloatField()),
                ('a52', models.BooleanField()),
            ],
        ),
    ]
